cookie:
  expiry_days: 30
  key: 8f82jf92jf92jf92jf92jf92jf92jf92
  name: ttrpg_buddy_auth
credentials:
  usernames:
    cheubner:
      email: cheubner@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Cullen Heubner
      password: $2b$12$Gl3btbNT9UDOGb8LeTuVvORkGHrJa7gePQycgUxDz8cZX29BMizvK
    kheubner:
      email: klhbnr@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Keel Heubner
      password: $2b$12$9xyk1hU4qSrvURAb3VpAfep07GwJT70/MTJpKM6jurRBvEUy0awES
    rheubner:
      email: ross.heubner@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Ross Heubner
      password: $2b$12$I2sycvc0T5sXZ6W/1c81l.BaeneYBRd9UsNGz2RSMc8ykWYNbdmEK
pre-authorized:
  emails: